# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welcome
email: webteam@canonical.com
description: Conjure-up lets you summon up a big-software stack as a 'spell' - a model of the stack, combined with extra know-how to get you from an installed stack to a fully usable one.
keywords: Conjure-up, OpenStack, Kubernetes, spell
baseurl: ""
asset_path: https://assets.ubuntu.com/v1/
navigation:
- text: Home
  url: /
exclude: [
  'LICENCE',
  'README.md',
  'gulpfile.babel.js',
  'package.json',
  'node_modules'
]
permalink: /:title

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# only build incrementally
incremental: true
